name: deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    if: github.repository == 'dominikg/flyhighivan'
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts
      - run: pnpm build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          clean: true
          single-commit: true
